version: 2.1

orbs:
    node: circleci/node@5.0.0
    aws: circleci/aws-cli@2.1.0
    eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
    build:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - node/install
            - aws/setup
            - eb/setup
            - checkout

            # Set up & deploy API artifacts
            - run:
                  name: Install API dependencies
                  command: |
                      npm run setup:api
            - run:
                  name: Build API from source code
                  command: |
                      npm run build:api
            - run:
                  name: Deploy API artifacts
                  command: |
                      npm run deploy:api

            # Set up & deploy UI artifacts 
            - run:
                  name: Install UI dependencies
                  command: |
                      npm run setup:ui
            - run:
                  name: Build UI from source code
                  command: |
                      npm run build:ui
            - run:
                  name: Deploy UI artifacts
                  command: |
                      npm run deploy:ui
